### ISSUE TITLE
Navigation no longer working; receiving 404 errors

### ISSUE THREAD

**Issue by josh-wong** [jdoiro3/mkdocs-multirepo-plugin#36] opened 2022-07-12 18:29 UTC
Hey hey.

My multirepo doc site was working fine up until yesterday, but when I checked it today, links to those docs sites in the side navigation all give 404 errors.

I've tried running workflows on the individual repos and the multirepo doc site to see if that helped, but neither of those attempts worked.

Were there any changes to how navigation is treated?

**Comment by jdoiro3** [comment] 2022-07-12 18:53
Rerun the workflow and pin the plugin version to `0.4.3`. The previous version had a bug. I was able to build your site locally and all links worked for me.

**Comment by jdoiro3** [comment] 2022-07-12 19:16
I'm going to close this again since I can't reproduce it. I am running into errors with the `git-revision-date` plugin but when I remove that the site seems to be built fine.

**Closed by jdoiro3** 2022-07-12 19:16 UTC

**Comment by josh-wong** [comment] 2022-07-12 19:37
Thanks for looking into this. 

Looks like the documentation for the `git-revision-date` plugin was recently updated: 
- [https://github.com/mkdocs-material/docs/setup/adding-a-git-repository.md](https://github.com/squidfunk/mkdocs-material/commit/3cce3ea9b172f06aefc831ae58fec2d4a26a8ea8#diff-6db7c4c5fb4d11609ecc9edbf73b3661bf36ae5a3aa1ea3fd3e4d84ea27074b7)

I'll do some testing later to see if updating the plugin name fixes the issue.

Appreciate your help!🙏🏻
